name: Build images
on:
  push:
    tags:
      - 'v*'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Get context
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        working-directory: .
        run: npm install --force
      
      - name: Build react
        working-directory: .
        run: npm run build
        env:
          CI: false
          REACT_APP_VERSION: ${{ steps.vars.outputs.tag }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Cache Docker layers
        uses: actions/cache@v3
        id: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Inmagik Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.inmagik.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          tags: docker.inmagik.com/wlm/webapp
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
